name: CI
on:
  pull_request:    
  push:
    branches: ["main", "windows-conda"]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build

      - name: Build and install TopoToolbox
        run: |
          pip install .[opensimplex]

      - name: Run tests
        run: |
          python -m pytest

      - name: Downgrade numpy
        run: |
          pip install matplotlib scipy rasterio "numpy==1.23.5" --upgrade --upgrade-strategy eager
          pytest
  conda-install:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: tt3
          channels: conda-forge
          conda-remove-defaults: true
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install tools
        run: pip install -r requirements.txt

      - name: Run pylint
        run: pylint --rcfile=pyproject.toml src/topotoolbox/

      - name: Run type checks
        run: mypy --ignore-missing-imports src/topotoolbox
